title: <p align="center"> Shobana </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/s-shobana-01760324/">LinkedIn</a> |
  <a href="https://github.com/Shobana-27">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Machine learning related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with Ugam Solutions to provide analytical solutions to US retailers.
  Working in Target as Sr. Data Analyst.
  <br>
  </p>



theme: jekyll-theme-minimal
